<?php
/**
 * @file
 */

define('MICROSERVICES_BATCH', 'microservices_batch');
define('MICROSERVICES_BATCH_STATUS_NEW', 'new');
define('MICROSERVICES_BATCH_STATUS_IN_PROGRESS', 'in progress');
define('MICROSERVICES_BATCH_STATUS_DONE', 'done');
define('MICROSERVICES_BATCH_STATUS_FAILED', 'failed');

/**
 * @param $message
 *
 * @throws \Exception
 */
function microservices_batch_create($message) {
  if (empty($message->params)) {
    throw new Exception('Batch should not be empty');
  }

  db_insert('microservices_batch')
    ->fields(array('message' => serialize($message), 'created' => time()))
    ->execute();
  $batch_id = (int) Database::getConnection()->lastInsertId();

  $query = db_insert('microservices_batch_items')
    ->fields(array('batch_id', 'name', 'weight', 'wait', 'message', 'status'));
  $weight = 0;
  foreach ($message->params as $name => $item) {
    if ($item->type == MICROSERVICES_MESSAGE_ACTION) {
      microservices_assert_action($item->service, $item->action);
    }
    elseif ($item->type == MICROSERVICES_MESSAGE_EVENT) {
      microservices_assert_event($item->event);
    }
    else {
      throw new Exception("Unknown task type: $item->type");
    }

    if (!empty($item->sender)) {
      throw new Exception('Sender should be empty in batch task');
    }

    $item->sender = MICROSERVICES_BATCH;
    $item->context = !empty($item->context) ? $item->context : NULL;
    $item->params = !empty($item->params) ? $item->params : NULL;

    $query->values(array(
      'batch_id' => $batch_id,
      'name' => $name,
      'weight' => ++$weight,
      'type' => $item->type,
      'wait' => !empty($item->wait) ? 1 : 0,
      'message' => serialize($item),
      'status' => MICROSERVICES_BATCH_STATUS_NEW,
    ));
  }
  $query->execute();

  microservices_batch_process_begin($batch_id);
}

function microservices_batch_load($id) {
  $batch = db_select('microservices_batch', 'bt')
    ->fields('bt')
    ->condition('id', $id)
    ->execute()
    ->fetchObject();

  if (!$batch) {
    throw new Exception('Batch not found');
  }

  $batch->id = (int) $batch->id;
  $batch->created = (int) $batch->created;
  $batch->message = unserialize($batch->message);

  $batch->items = db_select('microservices_batch_items', 'bt')
    ->fields('bt')
    ->condition('batch_id', $id)
    ->orderBy('weight')
    ->execute()
    ->fetchAllAssoc('name');

  foreach ($batch->items as &$item) {
    $item->id = (int) $item->id;
    $item->batch_id = (int) $item->batch_id;
    $item->wait = (bool) $item->wait;
    $item->message = unserialize($item->message);
  }

  return $batch;
}

function microservices_batch_process_begin($id) {
  $batch = microservices_batch_load($id);
  $in_progress = FALSE;
  foreach ($batch->items as $item) {
    // If locked item failed, break current batch.
    if ($item->wait && ($item->status == MICROSERVICES_BATCH_STATUS_FAILED)) {
      $in_progress = FALSE;
      break;
    }

    // Skip not new tasks.
    if ($item->status != MICROSERVICES_BATCH_STATUS_NEW) {
      if ($item->status == MICROSERVICES_BATCH_STATUS_IN_PROGRESS) {
        $in_progress = TRUE;
      }
      continue;
    }

    // All tasks should be processed before locked task will be processed.
    if ($item->wait && $in_progress) {
      break;
    }

    if (microservices_batch_item_process($item) == MICROSERVICES_BATCH_STATUS_IN_PROGRESS) {
      $in_progress = TRUE;
    }
  }

  // If batch not in progress send a result and remove it.
  if (!$in_progress) {
    microservices_batch_process_end($id);
  }
}

function microservices_batch_process_end($id) {
  $batch = microservices_batch_load($id);
  $error = NULL;
  foreach ($batch->items as &$item) {
    if (!$error && $item->wait && ($item->status == MICROSERVICES_BATCH_STATUS_FAILED)) {
      $error = $item->message->error;
    }

    // Unset batch useless batch attributes.
    unset($item->weight);
    unset($item->status);
    if (!empty($item->id)) {
      unset($item->id);
    }
    unset($item->batch_id);
    if (!empty($item->batch_id)) {
      unset($item->batch_id);
    }
    if (!empty($item->context->batch)) {
      unset($item->context->batch);
    }
  }

  // Add batch items to context.
  if (empty($batch->message->context)) {
    $batch->message->context = new stdClass();
  }
  $batch->message->context->batch = new stdClass();
  $batch->message->context->batch->items = $batch->items;

  // Send batch result.
  microservices_send_result($batch->message, !$error ? TRUE : NULL, $error);

  // Clear batch-related data.
  db_delete('microservices_batch')
    ->condition('id', $batch->id)
    ->execute();
  db_delete('microservices_batch_items')
    ->condition('batch_id', $batch->id)
    ->execute();
}

function microservices_batch_item_status($item, $status) {
  $values = array('status' => $status);
  // Remove message if event was done, because event should not have any result.
  if ($item->message->type == MICROSERVICES_MESSAGE_EVENT
      && $status == MICROSERVICES_BATCH_STATUS_DONE) {
    $values['message'] = NULL;
  }
  // Update item status.
  db_update('microservices_batch_items')
    ->fields($values)
    ->condition('id', $item->id)
    ->execute();
}

function microservices_batch_item_process($item) {
  if (empty($item->message->context)) {
    $item->message->context = new stdClass();
  }
  $item->message->context->batch = new stdClass();
  $item->message->context->batch->id = $item->batch_id;
  $item->message->context->batch->item_id = $item->id;
  if ($item->message->type == MICROSERVICES_MESSAGE_ACTION) {
    microservices_send_action(
      $item->message->service,
      $item->message->action,
      $item->message->params,
      $item->message->sender,
      $item->message->context
    );
    microservices_batch_item_status($item, MICROSERVICES_BATCH_STATUS_IN_PROGRESS);
    return MICROSERVICES_BATCH_STATUS_IN_PROGRESS;
  }
  elseif ($item->message->type == MICROSERVICES_MESSAGE_EVENT) {
    microservices_send_event(
      $item->message->event,
      $item->message->params,
      $item->message->context
    );
    microservices_batch_item_status($item, MICROSERVICES_BATCH_STATUS_DONE);
    return MICROSERVICES_BATCH_STATUS_DONE;
  }
  else {
    throw new Exception('Unknown task type');
  }
}

function microservices_batch_item_result($id, $message) {
  db_update('microservices_batch_items')
    ->fields(array(
      'message' => serialize($message),
      'status' => $message->error ? MICROSERVICES_BATCH_STATUS_FAILED : MICROSERVICES_BATCH_STATUS_DONE,
    ))
    ->condition('id', $id)
    ->execute();
}
