<?php
/**
 * @file
 */

/**
 * Implements hook_menu
 */
function microservices_ui_menu() {
  $items['admin/microservices'] = array(
    'title' => 'Microservices',
    'page callback' => 'microservices_ui_dashboard',
    'access arguments' => array('access microservices information'),
  );

  return $items;
}

/**
 * Implements hook_permission().
 */
function microservices_ui_permission() {
  return array(
    'access microservices information' => array(
      'title' => t('Access microservices information'),
    ),
  );
}

/**
 * Page callback for 'admin/microservices'
 */
function microservices_ui_dashboard() {
  $html = '<div id="dashboard"></div>';
  return $html;
}
