<?php
/**
 * @file
 */

define('MICROSERVICES_CRON', 'microservices_cron');

/**
 * Implements hook_hook_info();
 */
function microservices_cron_hook_info() {
  return array(
    'microservices_cron_info' => array(
      'group' => 'microservices',
    ),
  );
}

/**
 * @return array
 */
function microservices_cron_info() {
  $cache = &drupal_static(__FUNCTION__);

  if (!isset($cache)) {
    $cache = module_invoke_all('microservices_cron_info');
    drupal_alter('microservices_cron_info', $cache);
  }

  return $cache;
}
